/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kandavela' at '4/26/16 11:11 AM' with Gradle 2.6
 *
 * @author kandavela, @date 4/26/16 11:11 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
